services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    environment:
        - JEKYLL_ENV=development
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll